# Specify Docker Version
version: "3.8"

# Specify Each service or Image to run
services:
  # Service Identifier
  mongodb:
    # Service/Image to Run
    image: mongo
    # Service name (Always matches service identifier)
    container_name: mongodb
    # port mapping from:to
    ports:
      - 27017:27017
    # specific volume mapping for service
    volumes:
      - data:/data
    # specified environment variables for image
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  server:
    # image: 343218221384.dkr.ecr.us-east-1.amazonaws.com/balisongflippingcenter/backend/main:latest
    build: .
    container_name: server
    ports:
      - 8080:8080
    # tell docker compose that this service depends on another service and must run afterwards
    depends_on:
      mongodb:
        condition: service_started
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

# Volumes to set up disk space on hardware for each service
volumes:
  data: {}
