name: Build and Push Docker Image to ECR

# runs when code is merged to master or directly pushed to master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      -master

# necessary for secrets to be read
permissions:
  contents: read

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-latest
    environment: Deployment   # necessary to match where the secret variables are

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag the Docker image then push to ecr
        run: |
          docker build --no-cache -t balisongflippingcenter/backend/main .
          docker tag balisongflippingcenter/backend/main:latest 343218221384.dkr.ecr.us-east-1.amazonaws.com/balisongflippingcenter/backend/main:latest
          docker push 343218221384.dkr.ecr.us-east-1.amazonaws.com/balisongflippingcenter/backend/main:latest
